### PR TITLE
Support include directives on shaderc

### PR DESCRIPTION
**Pull request by fand**
image

Hello 👋 Thanks for great library!! 

I was tweaking around notan_macro to see if it's possible to support `#include`. 
Then I found `shaderc` can handle `#include` directives by passing an additional option.

So, this PR adds an option passed to `shaderc` to include shader files in following format:

- Relative includes `#include "foo/bar.glsl"`
  - This tries to read "foo/bar.glsl" relative to the input shader file.
- Standard includes `#include <foo/bar.glsl>`
  - This tries to read "foo/bar.glsl" under the root directory (`CARGO_MANIFEST_DIR` or `.`)

Also I added `examples/shaders/draw_shader_include.glsl`, an example file to test `#include`.
You can run it by `cargo run --example draw_shader_include --features shaderc`.

NOTE: include directive only works on `include_fragment_shader!` / `include_vertex_shader!`  macros, not on `fragment_shader!` / `vertex_shader!` because it's difficult to determine the directory to search for the include files.

### CODE REVIEW

**Comment by Nazariglez** [comment]
This is great, thank you so much!

**Comment by Nazariglez** [comment]
This is failing because shaderc is disabled on the build system by default, mainly because docs were not building for crates, so I need to check how to enable it only for the build system. Another option is avoid the compilation of the example if shaderc is not enabled. I'll take a look today.

**Comment by Nazariglez** [comment]
@fand is it ok to you if we remove the example? Only the example. 

I wasn't able to find a way to exclude the example from the `cargo test` command, it seems that `cargo` itself have some issues open related to this. The only options I can see is to enable `shaderc` on the ci machine, however I am not a big fan of this solution, because it will try to compile it on each build, and is a big dependency. So I am more inclined to just remove the example, because is a `niche` feature. 

What do you think?

**Comment by fand** [comment]
Thanks for review!

> So I am more inclined to just remove the example, because is a niche feature.

Yeah I totally agree 👍  I'll remove the example

> it seems that cargo itself have some issues open related to this

Just curious, could you give me the link of the issue if you have?

**Comment by Nazariglez** [comment]
This is the issue I found: https://github.com/rust-lang/cargo/issues/7233 they are trying to avoid the compilation using a config flag (I did it with `not(feature=shaderc)`), however this doesn't work. Using `cargo test --workspace --exclude my_example` does not work either. That's why I thought about to remove the example.

Sorry for the inconveniences and thank you so much for the PR!

**Pull request merged**
