### PR TITLE
Allow HtmlImagElement to be loaded (and potentially another texture types)

### LINKED ISSUE #135: Use non [u8] textures
Hey 👋 

First of all, amazing project. We're using notan for a video editing app we're building (web is our primary target) and so far it feels rather nice!

We've hit a small snag on assets. It seems current strategy is to load images into wasm memory?
Folks can upload very large / very many images on our app, and since wasm has a [hard limit on memory](https://v8.dev/blog/4gb-wasm-memory), we might run out 😅 

An alternative is to use HTMLImageElement / ImageBitmap and blit it directly, with [texImage2D](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D)

Is there a way to achieve this with notan rn? Did look around but could be I missed something 😄 

Possible solutions
- expose underlying backend context ([maybe something similar to egui's callbacks?](https://github.com/emilk/egui/blob/master/crates/egui_demo_app/src/apps/custom3d_glow.rs#L65))
- support non [u8] texture sources within notan directly (had a rough go at it [here](https://github.com/jawadsh123/notan/commit/82f4d2febcfabde75552ba086f22a787854bb042), though dunno if it's the right approach)

### PR DESCRIPTION
**Pull request by Nazariglez**
fixes #135

### CODE REVIEW

**Comment by Nazariglez** [comment]
Hey, @jawadsh123 this is ready. It was harder than I thought to find good architecture but I think that this will work. 

You should be able to load `HtmlImageElememt` with `TextureBuilder::from_html_image(&element)` if you import `notan::prelude::*`. You can also update texture with `TextureUpdater::with_html_imagr(&el)`. 

We can extend it easily by implementing `TextureSource` to any struct, for the Html types I have [this code](https://github.com/Nazariglez/notan/blob/52c5d77c2059479588524b3dea801ecbc6c8e304/crates/notan_glow/src/html_image.rs) that can be used as an example. 

Anyway, let me know what do you think, if you see something wrong or if you have any advice/improvement.

**Comment by jawadsh123** [comment]
ohh nice! lemme take a deeper look 🧐

**Comment by jawadsh123** [comment]
gave it a spin, TextureSourceHtmlImage worked fab 👌 
also tried to create a custom source for VideoFrames but there's a hiccup
doing so requires access to `GlowBackend` struct and `gl` field within it, which are not public
after exposing those everything worked!

`GlowBackend` we could add to prelude, though dunno about `gl`, if exposing the field directly is a good idea or there should be a `getter` method 🤷

**Comment by Nazariglez** [comment]
GlowBackend is now on the prelude, and I just made public `gl`. People using it will need to downcast manually and know how to use `OpenGL` so I think it's safe to assume that, if they do that, they know what they are doing, and protecting gl behind a method will add nothing.

Thank you so much for testing it!

**Comment by jawadsh123** [comment]
woohoo! 💜

**Pull request merged**
