### PR TITLE
Added a feature to use a custom GL config for wayland and nvidia machines

### PR DESCRIPTION
**Pull request by Nazariglez**

### CODE REVIEW

**Comment by riverfr0zen** [comment]
Just tried the feature out on Wayland but still getting the same dmabufs error. Here is the log of how I tested it:

```
/tmp$ git clone https://github.com/Nazariglez/notan.git
Cloning into 'notan'...
remote: Enumerating objects: 10637, done.
remote: Counting objects: 100% (962/962), done.
remote: Compressing objects: 100% (393/393), done.
remote: Total 10637 (delta 630), reused 871 (delta 563), pack-reused 9675
Receiving objects: 100% (10637/10637), 26.84 MiB | 54.54 MiB/s, done.
Resolving deltas: 100% (7063/7063), done.
/tmp$ cd notan/
/tmp/notan$ git checkout f/wayland-nvidia
Branch 'f/wayland-nvidia' set up to track remote branch 'f/wayland-nvidia' from 'origin'.
Switched to a new branch 'f/wayland-nvidia'
/tmp/notan$ git pull origin f/wayland-nvidia
From https://github.com/Nazariglez/notan
 * branch            f/wayland-nvidia -> FETCH_HEAD
Already up to date.
/tmp/notan$ cargo run --features nvidia-wayland --example draw_rect
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.137
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling pkg-config v0.3.26
   Compiling version_check v0.9.4
   Compiling once_cell v1.16.0
   Compiling libm v0.2.6
   Compiling bitflags v1.3.2
   Compiling log v0.4.17
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.10.0
   Compiling xml-rs v0.8.4
   Compiling lazy_static v1.4.0
   Compiling memchr v2.5.0
   Compiling bytemuck v1.12.3
   Compiling arrayref v0.3.6
   Compiling num-traits v0.2.15
   Compiling memoffset v0.6.5
   Compiling lock_api v0.4.9
   Compiling parking_lot_core v0.9.4
   Compiling adler v1.0.2
   Compiling typenum v1.15.0
   Compiling crc32fast v1.3.2
   Compiling miniz_oxide v0.5.4
   Compiling jobserver v0.1.25
   Compiling cc v1.0.76
   Compiling num-integer v0.1.45
   Compiling miniz_oxide v0.6.2
   Compiling flate2 v1.0.24
   Compiling byte-tools v0.2.0
   Compiling num-bigint v0.4.3
   Compiling block-buffer v0.3.3
   Compiling libloading v0.7.4
   Compiling cmake v0.1.49
   Compiling getrandom v0.2.8
   Compiling png v0.17.7
   Compiling fake-simd v0.1.2
   Compiling downcast-rs v1.2.0
   Compiling parking_lot v0.12.1
   Compiling futures-core v0.3.25
   Compiling dlib v0.5.0
   Compiling generic-array v0.9.1
   Compiling wayland-scanner v0.29.5
   Compiling slab v0.4.7
   Compiling num-rational v0.4.1
   Compiling num-iter v0.1.43
   Compiling digest v0.7.6
   Compiling sha2 v0.7.1
   Compiling ahash v0.7.6
   Compiling futures-channel v0.3.25
   Compiling pin-project-lite v0.2.9
   Compiling futures-task v0.3.25
   Compiling khronos_api v3.1.0
   Compiling spirv_cross v0.23.1
   Compiling glsl-to-spirv v0.1.7
   Compiling freetype-sys v0.13.1
   Compiling wayland-sys v0.29.5
   Compiling glam v0.21.3
   Compiling instant v0.1.12
   Compiling futures-sink v0.3.25
   Compiling crossbeam-utils v0.8.12
   Compiling futures-util v0.3.25
   Compiling thiserror v1.0.37
   Compiling ttf-parser v0.17.1
   Compiling fastrand v1.8.0
   Compiling remove_dir_all v0.5.3
   Compiling tempfile v3.3.0
   Compiling expat-sys v2.1.6
   Compiling num-complex v0.4.2
   Compiling nix v0.24.2
   Compiling ab_glyph_rasterizer v0.1.7
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.25
   Compiling hashbrown v0.12.3
   Compiling wayland-client v0.29.5
   Compiling gl_generator v0.14.0
   Compiling notan_math v0.8.0 (/tmp/notan/crates/notan_math)
   Compiling num v0.4.0
   Compiling crossbeam-epoch v0.9.11
   Compiling byteorder v1.4.3
   Compiling color_quant v1.1.0
   Compiling jpeg-decoder v0.3.0
   Compiling notan_utils v0.8.0 (/tmp/notan/crates/notan_utils)
   Compiling owned_ttf_parser v0.17.1
   Compiling rand_core v0.6.4
   Compiling servo-fontconfig-sys v5.1.0
   Compiling ab_glyph v0.2.18
   Compiling indexmap v1.9.1
   Compiling slotmap v1.0.6
   Compiling minimal-lexical v0.2.1
   Compiling scoped-tls v1.0.1
   Compiling rayon-core v1.9.3
   Compiling image v0.24.5
   Compiling wayland-commons v0.29.5
   Compiling nom v7.1.1
   Compiling wayland-protocols v0.29.5
   Compiling x11-dl v2.20.0
   Compiling ppv-lite86 v0.2.17
   Compiling notan_core v0.8.0 (/tmp/notan/crates/notan_core)
   Compiling serde_derive v1.0.147
   Compiling cfg_aliases v0.1.1
   Compiling notan_input v0.8.0 (/tmp/notan/crates/notan_input)
   Compiling rand_chacha v0.3.1
   Compiling crossbeam-deque v0.8.2
   Compiling crossbeam-channel v0.5.6
   Compiling num_cpus v1.14.0
   Compiling crossfont v0.5.1
   Compiling smithay-client-toolkit v0.16.0
   Compiling rayon v1.5.3
   Compiling cty v0.2.2
   Compiling serde v1.0.147
   Compiling vec_map v0.8.2
   Compiling foreign-types-shared v0.3.1
   Compiling servo-fontconfig v0.5.1
   Compiling rand v0.8.5
   Compiling xcursor v0.3.4
   Compiling glutin_egl_sys v0.3.1
   Compiling wayland-cursor v0.29.5
   Compiling glutin_glx_sys v0.3.0
   Compiling freetype-rs v0.26.0
   Compiling euclid v0.22.7
   Compiling memmap2 v0.5.8
   Compiling wayland-sys v0.30.0
   Compiling safe_arch v0.5.2
   Compiling tiny-skia-path v0.7.0
   Compiling arrayvec v0.5.2
   Compiling either v1.8.0
   Compiling futures-macro v0.3.25
   Compiling thiserror-impl v1.0.37
   Compiling glsl-layout-derive v0.4.0
   Compiling foreign-types-macros v0.2.2
   Compiling arrayvec v0.7.2
   Compiling lyon_geom v1.0.3
   Compiling tiny-skia v0.7.0
   Compiling raw-window-handle v0.5.0
   Compiling glutin v0.30.2
   Compiling approx v0.5.1
   Compiling glsl-layout v0.4.2
   Compiling ahash v0.8.2
   Compiling foreign-types v0.5.0
   Compiling xi-unicode v0.3.0
   Compiling static_assertions v1.1.0
   Compiling linked-hash-map v0.5.6
   Compiling rustc-hash v1.1.0
   Compiling twox-hash v1.6.3
   Compiling glyph_brush_layout v0.2.3
   Compiling lyon_path v1.0.2
   Compiling raw-window-handle v0.4.3
   Compiling glutin-winit v0.2.1
   Compiling ordered-float v3.4.0
   Compiling mio v0.8.5
   Compiling itoa v1.0.4
   Compiling percent-encoding v2.2.0
   Compiling float_next_after v0.1.5
   Compiling atty v0.2.14
   Compiling nohash-hasher v0.2.0
   Compiling calloop v0.10.2
   Compiling glyph_brush_draw_cache v0.1.5
   Compiling emath v0.20.0
   Compiling ecolor v0.20.0
   Compiling glow v0.11.2
   Compiling serde_json v1.0.87
   Compiling colored v1.9.3
   Compiling glyph_brush v0.7.5
   Compiling epaint v0.20.0
   Compiling lyon_tessellation v1.0.5
   Compiling lyon_algorithms v1.0.2
   Compiling ryu v1.0.11
   Compiling num_threads v0.1.6
   Compiling time-core v0.1.0
   Compiling time v0.3.17
   Compiling fern v0.6.1
   Compiling enum-map-derive v0.10.0
   Compiling lyon v1.0.1
   Compiling rand_pcg v0.3.1
   Compiling egui v0.20.0
   Compiling tracing-core v0.1.30
   Compiling notan_random v0.8.0 (/tmp/notan/crates/notan_random)
   Compiling futures-executor v0.3.25
   Compiling platter2 v0.1.6
   Compiling futures v0.3.25
   Compiling tracing v0.1.37
   Compiling unicode_names2 v0.6.0
   Compiling sctk-adwaita v0.4.3
   Compiling winit v0.27.5
   Compiling egui_extras v0.20.0
   Compiling enum-map v2.4.1
   Compiling egui_demo_lib v0.20.0
   Compiling notan_macro v0.8.0 (/tmp/notan/crates/notan_macro)
   Compiling notan_graphics v0.8.0 (/tmp/notan/crates/notan_graphics)
   Compiling notan_app v0.8.0 (/tmp/notan/crates/notan_app)
   Compiling notan_glow v0.8.0 (/tmp/notan/crates/notan_glow)
   Compiling notan_glyph v0.8.0 (/tmp/notan/crates/notan_glyph)
   Compiling notan_winit v0.8.0 (/tmp/notan/crates/notan_winit)
   Compiling notan_log v0.8.0 (/tmp/notan/crates/notan_log)
   Compiling notan_backend v0.8.0 (/tmp/notan/crates/notan_backend)
   Compiling notan_text v0.8.0 (/tmp/notan/crates/notan_text)
   Compiling notan_draw v0.8.0 (/tmp/notan/crates/notan_draw)
   Compiling notan v0.8.0 (/tmp/notan)
    Finished dev [unoptimized + debuginfo] target(s) in 38.05s
     Running `target/debug/examples/draw_rect`
2022-12-29 19:02:48 [crossfont::ft] DEBUG: Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
2022-12-29 19:02:48 [notan_glow] INFO: Using opengl graphics api
[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
/tmp/notan$ 


```

**Comment by Nazariglez** [comment]
Well, this is a boomer haha. Right now it's using the same configuration, so the error must be elsewhere. I am not allocating more time for this for now, so let's leave this open for a while to see if anybody have hints or something, but I have no hopes until nvidia improves wayland support. 

Thanks for the help!

**Comment by Nazariglez** [comment]
Hey @riverfr0zen, I am thinking that we changed how the GL Context is acquired in the lastest (`0.9.2`) version, maybe, just maybe wayland could works now? It did help with some errors on windows, who knows. If you have time, no rush at all, and you can try using the latest version on crates, or the branchs `develop` or `main`, that would be awesome. 

Thanks!

**Comment by riverfr0zen** [comment]
Just checked with  notan-0.9.2, but sadly no change.

**Comment by Nazariglez** [comment]
What a bummer, thanks for taking the time to test it.

**Comment by Nazariglez** [comment]
Closing, no point on keep this open for now, we can check again in the future if there is any change.

**Pull request closed without merging**
