### PR TITLE
add a simple CI action

### PR DESCRIPTION
**Pull request by jawadsh123**
a simple CI action that does some linting and runs tests ✨ 
mostly stolen from [here](https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml)

### CODE REVIEW

**Comment by jawadsh123** [comment]
@Nazariglez seems you might've [to approve](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) for this to run 😬

**Review by Nazariglez — APPROVED** [review]
lgtm!

**Comment by jawadsh123** [comment]
oops, tests are breaking on CI it seems, will fix in a follow-up 😇

**Comment by Nazariglez** [comment]
No worries! Whenever it's ready it will be great, no rush"

**Pull request merged**
