### PR TITLE
notan_egui: Support clipboard on desktop.

### PR DESCRIPTION
**Pull request by ar37-rs**

### CODE REVIEW

**Comment by Nazariglez** [comment]
Hello @ar37-rs!

 Thanks for the PR! Let me check it and I'll come back to you.

**Comment by ar37-rs** [comment]
@Nazariglez never mind, don't worry. i was just experimenting. tested bith on linux and windows so far.

**Review by Nazariglez — APPROVED** [review]
lgtm!

**Comment by Nazariglez** [comment]
Hey @ar37-rs, this looks good to me! I would like to make some minor changes, but this is excellent work, thank you so much!

**Pull request merged**
