### PR TITLE
Enable always on top for window

### PR DESCRIPTION
**Pull request by woelper**
This PR enables a window to be always on top.
This feature is both present at window creation and can be toggled while running (similar to fullscreen)

### CODE REVIEW

**Comment by Nazariglez** [comment]
This looks great to me, thank you so much!

fixes #129

**Comment by Nazariglez** [comment]
@woelper I forget about the Changelog, can you add a new PR with the change added on it?

**Comment by woelper** [comment]
@Nazariglez Sure, I'll do a PR to the changelog. I am just unsure about the next version that will be released, what version number are you planning on?

**Comment by woelper** [comment]
@Nazariglez Changelog PR: https://github.com/Nazariglez/notan/pull/134

**Pull request merged**
