### PR TITLE
Allow u16 index buffers

### LINKED ISSUE #163: Use different types of index buffers with Pipelines
right now index buffer type is pinned to `glow::UNSIGNED_INT`
https://github.com/Nazariglez/notan/blob/f2cc8397fe783ef2553aeb09f40d89402d412f86/crates/notan_glow/src/lib.rs#L342-L343

I'm working with a lib that gives me back u16 buffers, which I then have to _upgrade_ to u32 causing an extra copy!
would be nice to be able to upload them directly

do you feel this should be supported?
if yes, in terms of API I'm thinking there could be a `with_info` on `IndexBufferBuilder` and a `IndexFormat` enum that captures all the types, wdyt?

### PR DESCRIPTION
**Pull request by Nazariglez**
closes #163

### CODE REVIEW

**Comment by jawadsh123** [comment]
looking nice 👌 

a slightly tangential observation
`with_data` for all the three buffers takes different i/p
- for VertexBufferBuilder it takes `&[f32]`
- for IndexBufferBuilder it takes `&[u32]`
- for UniformBufferBuilder it takes `BufferData`

while `set_buffer_data` is buffer agnostic and always takes `BufferData`
wondering if there's value in unifying all to `BufferData`?

**Comment by Nazariglez** [comment]
We could. Though I am not sure if it is worth it, taking a trait generates worst error messages, I am not sure about if anyone will need to pass other types to the index buffer or the vertex either, and it will add some complexity to the code too. I guess it's possible, not a big fan of it right now if we don't have a strong use case.

What are your thoughts on it?

PD: Closing but we can keep talking about the types.

**Comment by jawadsh123** [comment]
don't have a strong case for it, was just wondering for consistency 😅 
though now that I think about it more deeply, `f32` for vertices and `u32` for indices actually make total sense for the general use case
and for the odd outliers, `set_buffer_data` does it :)

**Comment by Nazariglez** [comment]
Yeah, methods that do the same with different types... is weird. I see the problem there. Though it may be fine for now. We can revisit this again at any time if you think we need to. Thanks!

**Pull request merged**
