### PR TITLE
add support for passing a window position upon creation

### PR DESCRIPTION
**Pull request by jonatino**
This allows a window to spawn at the specified position and wont lead to odd "jumping" behavior we see right now after setting the position after window creation.

Clamping logic is from here: https://github.com/Shel-M/egui/blob/master/crates/egui-winit/src/window_settings.rs#LL91C10-L91C10

### CODE REVIEW

**Comment by Nazariglez** [comment]
hey @jonatino thanks for this! it looks good, would you like to add a line to the changelog yourself?

**Review by Nazariglez — APPROVED** [review]

**Comment by jonatino** [comment]
@Nazariglez updated the changelog.

**Comment by jonatino** [comment]
@Nazariglez please run lint checker task again, all errors should be fixed now.

**Comment by Nazariglez** [comment]
All good, thanks!

**Pull request merged**
